name: remote_logger
description: A listener for logging library to post logs to remote storage.
version: 0.1.0+2
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  async: ^2.5.0
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.2
  mews_pedantic: ^0.5.0
  mockito: ^5.0.16
  test: ^1.18.0
