name: storybook
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  optimus:
    path: ../optimus
  shared_preferences: ^2.0.16
  storybook_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.15.0
  path: ^1.8.2
flutter:
  uses-material-design: true
