name: optimus
description: Optimus is a design system for mobile platforms (and web in future) used internally in Mews.
version: 0.1.0
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dfunc: ^0.5.2
  flutter:
    sdk: flutter
  flutter_slidable: ^0.5.4
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.1.1

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: packages/optimus/fonts/Montserrat-Regular.ttf
        - asset: packages/optimus/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: packages/optimus/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: OptimusIcons
      fonts:
        - asset: packages/optimus/fonts/OptimusIcons.ttf
