name: optimus
description: Optimus is a design system for mobile platforms (and web in future) used internally in Mews.
version: 0.38.3+1
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  dfunc: ^0.10.0
  flutter:
    sdk: flutter
  flutter_slidable: ">=1.2.0 <4.0.0"
  flutter_svg: ^2.0.7
  freezed_annotation: ">=1.0.0 <3.0.0"
  intl: ">=0.17.0 <0.20.0"
  optimus_icons: ^0.1.1+2
  theme_tailor_annotation: "^3.0.0"

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ">=1.0.0 <3.0.0"
  mews_pedantic: ^0.35.0
  theme_tailor: "^3.0.0"
flutter:
  assets:
    - assets/
    - assets/light/
    - assets/dark/
  fonts:
    - family: Inter
      fonts:
        - asset: packages/optimus/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/optimus/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/optimus/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/optimus/fonts/Inter-Bold.ttf
          weight: 700