name: optimus
description: Optimus is a design system for mobile platforms (and web in future) used internally in Mews.
version: 0.5.0+1
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dfunc: ^0.6.0
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0-nullsafety.0
  freezed_annotation: ^0.14.0
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0
  mews_pedantic: ^0.2.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: packages/optimus/fonts/Montserrat-Regular.ttf
        - asset: packages/optimus/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: packages/optimus/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: OptimusIcons
      fonts:
        - asset: packages/optimus/fonts/OptimusIcons.ttf
