name: optimus_widgetbook
description: "Widgetbook for Optimus Design System by Mews"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  accessibility_tools: ^2.4.0
  dfunc: 0.10.0
  flutter:
    sdk: flutter
  optimus:
    path: ../optimus
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.38.0
  widgetbook_generator: ^3.9.0
flutter:
  uses-material-design: true
