name: mews_pedantic
description: Dart and Flutter static analysis and lint rules incorporated in Mews.
version: 0.12.0
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  dart_code_metrics: 5.5.0
  meta: ^1.7.0
