name: mews_pedantic
description: Dart and Flutter static analysis and lint rules incorporated in Mews.
version: 0.10.0
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_code_metrics: ">=4.21.2 <6.0.0"
  meta: ^1.7.0
