name: mews_pedantic
description: Dart and Flutter static analysis and lint rules incorporated in Mews.
version: 0.3.0
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
