name: mews_pedantic
description: Dart and Flutter static analysis and lint rules incorporated in Mews.
version: 0.42.1
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  meta: ^1.7.0
