name: mews_pedantic
description: Dart and Flutter static analysis and lint rules incorporated in Mews.
version: 0.4.0-dev.5
repository: https://github.com/MewsSystems/mews-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_code_metrics: ^4.9.0
  flutter_lints: ^1.0.4
  meta: ^1.7.0
