name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.10.1 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  optimus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.42.3
