name: Check Storybook
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: storybook/
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter packages pub get
        working-directory: optimus/
      - run: flutter packages pub run build_runner build
        working-directory: optimus/
      - run: flutter pub get
      - run: flutter format . --set-exit-if-changed
        name: Ensure proper formatting
      - run: bash ../tool/analyze.sh
        name: Check for errors and warnings
